frase = '     curso em vídeo python    '.strip()
dividido = frase.split(' ')
print(frase.upper())
print(len(frase.strip()))
print(frase.replace('python', 'programming').strip())
print('python' in frase)
print(frase.find('python'))
print(dividido)
print(dividido[0][3])